; BNF grammar for the dogue protocol

<message> ::= (<command>)*

<command> ::= '/' <op> <space> <user> <space> <args>? '\0'

<op> ::= 'ping' | 'pong' | 'say'

<user> ::= [\w]+

<args> ::= (<arg>) (' ' <arg>)*

<arg> ::= [ ^ <space> '\0' ]+ | '"'

<space> = (' ')+
