#!/usr/bin/env bash
procname=python
num=`pgrep $procname | wc -l`
if [[ $num -gt 1 ]] ; then
    echo Found more than one process to kill:
    pgrep $procname
    echo Cannot disambiguate. Aborting.
    exit 1
fi
killall $procname &> /dev/null
/sbin/start-stop-daemon -b -S -o --user doge --name build-server --no-close --chuid doge:doge --exec /bin/bash -- -c "python /home/doge/whatever/build-server.py" > /var/log/doge/error.log 2>&1

