#!/bin/bash

### BEGIN INIT INFO
# Provides:          raven
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Build server for dogue
# Description: Build server for dogue
### END INIT INFO
TIME=`date +%s`
RAVEN_PATH="/home/doge/dogue_bin"

DAEMON_PATH="$RAVEN_PATH/"
DAEMON=/usr/bin/raven
DAEMONOPTS="-jar $RAVEN_PATH/raven.jar --log /var/log/raven --timestamp $RAVEN_PATH/timestamp --lastRunFile $RAVEN_PATH/last"
DAEMONLOG="/var/log/raven/daemon-start_$TIME.log"
NAME=raven

PIDFILE=/var/run/$NAME.pid
SCRIPTNAME=/etc/init.d/$NAME
if [[ "$2" = "--debug" ]] ; then
    echo "Debugging mode"
    OUTPUT="$DAEMONLOG"
    HASLOG=true
else
    OUTPUT="/dev/null"
    HASLOG=false
fi
case "$1" in
start)
    echo "Starting $NAME"
    cd $DAEMON_PATH
    $DAEMON $DAEMONOPTS --command '/etc/init.d/starfire restart' > $OUTPUT 2>&1 &
    if [[ $? -eq 0 ]] ; then
        echo "Service started successfully"
    else
        echo "Service failed to start"
        if $HASLOG ; then
            cat $OUTPUT
        fi
    fi
;;
status)
    echo "Status of $NAME:"
    pgrep --exact $NAME &> /dev/null
    if [[ $? -eq 0 ]] ; then
        echo "Service is running"
    else
        echo "Service not running"
    fi
;;
stop)
    echo "Stopping $NAME"
    pgrep --exact $NAME &> /dev/null
    if [[ $? -eq 0 ]]; then
        pkill -9 --full --echo --exact $NAME
        echo "Stopped"
    else
        echo "Already dead"
    fi
;;
force-reload)
    $0 restart
;;
restart)
    $0 stop
    $0 start
;;

*)
    echo "Invalid argument: $0"
    echo "Options:"
    for i in start\
             stop\
             restart\
             status\
             force-reload ; do
        echo "    $i"
    done
    exit 1
esac
