#!/bin/bash

### BEGIN INIT INFO
# Provides:          raven
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Build server for dogue
# Description: Build server for dogue
### END INIT INFO
TIME=`date +%Y-%M-%d_%H-%M-%S`

DAEMON_PATH="/home/doge/dogue/dogue_bin/"
DAEMON=java
DAEMONOPTS="-jar $DAEMON_PATH/raven.jar --log /var/log/raven --timestamp $DAEMON_PATH/timestamp --lastRunFile $DAEMON_PATH/dogue_bin/last --command /var/init.d/starfire restart"
DAEMONLOG="/var/log/starfire/daemon-fail_$TIME.log"
NAME=raven
MUSER=root
DESC="Build server for dogue"

PIDFILE=/var/run/$NAME.pid
SCRIPTNAME=/etc/init.d/$NAME
if [ "$2" -eq "--debug-launch" ] ; then
    OUTPUT="$DAEMONLOG"
    HASLOG=true
else
    OUTPUT="/dev/null"
    HASLOG=false
fi
case "$1" in
start)
    printf "%-50s" "Starting $NAME..."
    cd $DAEMON_PATH

    PID=`su -l $MUSER -c "$DAEMON $DAEMONOPTS" > $OUTPUT 2>&1 & echo $!`
    #echo "Saving PID" $PID " to " $PIDFILE
        if [ -z $PID ]; then
            printf "%s\n" "Fail"
            if $HASLOG ; then
                cat $OUTPUT
            fi
        else
            echo $PID > $PIDFILE
            printf "%s\n" "Ok"
        fi
;;
status)
        printf "%-50s" "Checking $NAME..."
        if [ -f $PIDFILE ]; then
            PID=`cat $PIDFILE`
            if [ -z "`ps axf | grep ${PID} | grep -v grep`" ]; then
                printf "%s\n" "Process dead but pidfile ($PIDFILE) exists"
            else
                echo "Running"
            fi
        else
            printf "%s\n" "Service not running"
        fi
;;
stop)
        printf "%-50s" "Stopping $NAME"
            PID=`cat $PIDFILE`
            cd $DAEMON_PATH
        if [ -f $PIDFILE ]; then
            kill -HUP $PID
            printf "%s\n" "Ok"
            rm -f $PIDFILE
        else
            printf "%s\n" "pidfile not found"
        fi
;;
force-reload)
    $0 restart
;;
restart)
    $0 stop
    $0 start
;;

*)
        echo "Usage: $0 {status|start|stop|restart}"
        exit 1
esac
