#!/bin/bash

### BEGIN INIT INFO
# Provides:          starfire
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Game server for dogue
# Description: Game server for dogue
### END INIT INFO
TIME=`date +%Y-%m-%d_%H-%M-%S`

DAEMON_PATH="/home/doge/dogue_bin/"
DAEMON=/usr/bin/starfire
DAEMONOPTS="-jar $DAEMON_PATH/starfire.jar --log /var/log/starfire"
DAEMONLOG="/var/log/starfire/daemon-start_$TIME.log"
NAME=starfire
DAEMON_USER=root

PIDFILE=/var/run/$NAME.pid
SCRIPTNAME=/etc/init.d/$NAME
if [[ "$2" = "--debug" ]] ; then
    echo "Debugging mode"
    OUTPUT="$DAEMONLOG"
    HASLOG=true
else
    OUTPUT="/dev/null"
    HASLOG=false
fi
case "$1" in
start)
    echo "Starting $NAME"
    cd $DAEMON_PATH
    $DAEMON $DAEMONOPTS > $OUTPUT 2>&1 &
    if [[ $? -eq 0 ]] ; then
        echo "Service started successfully"
    else
        echo "Service failed to start"
        if $HASLOG ; then
            cat $OUTPUT
        fi
    fi
;;
status)
    echo "Status of $NAME:"
    pgrep --full --exact $NAME &> /dev/null
    if [[ $? -eq 0 ]] ; then
        echo "Service is running"
    else
        echo "Service not running"
    fi
;;
stop)
    echo "Stopping $NAME"
    pgrep --full --exact $NAME &> /dev/null
    echo "ss"
    if [[ $? -eq 0 ]]; then
        pkill -9 --full --echo --exact $NAME
        echo "Stopped"
    else
        echo "Already dead"
    fi
;;
force-reload)
    $0 restart
;;
restart)
    $0 stop
    $0 start
;;

*)
    echo "Invalid argument: $0"
    echo "Options:"
    for i in start\
             stop\
             restart\
             status\
             force-reload ; do
        echo "    $i"
    done
    exit 1
esac
